const BANK_CODES = [
  // =========================
  // COMMERCIAL BANKS
  // =========================
  { code: "044", name: "ACCESS BANK", category: "Commercial" },
  { code: "023", name: "CITIBANK NIGERIA", category: "Commercial" },
  { code: "050", name: "ECOBANK NIGERIA", category: "Commercial" },
  { code: "084", name: "ENTERPRISE BANK", category: "Commercial" },
  { code: "070", name: "FIDELITY BANK", category: "Commercial" },
  { code: "011", name: "FIRST BANK OF NIGERIA", category: "Commercial" },
  { code: "214", name: "FIRST CITY MONUMENT BANK (FCMB)", category: "Commercial" },
  { code: "103", name: "GLOBUS BANK", category: "Commercial" },
  { code: "058", name: "GUARANTY TRUST BANK (GTBANK)", category: "Commercial" },
  { code: "030", name: "HERITAGE BANK", category: "Commercial" },
  { code: "301", name: "JAIZ BANK", category: "Commercial" },
  { code: "082", name: "KEYSTONE BANK", category: "Commercial" },
  { code: "303", name: "LOTUS BANK", category: "Commercial" },
  { code: "107", name: "OPTIMUS BANK", category: "Commercial" },
  { code: "104", name: "PARALLEX BANK", category: "Commercial" },
  { code: "076", name: "POLARIS BANK", category: "Commercial" },
  { code: "105", name: "PREMIUMTRUST BANK", category: "Commercial" },
  { code: "101", name: "PROVIDUS BANK", category: "Commercial" },
  { code: "106", name: "SIGNATURE BANK", category: "Commercial" },
  { code: "068", name: "STANDARD CHARTERED BANK", category: "Commercial" },
  { code: "232", name: "STERLING BANK", category: "Commercial" },
  { code: "100", name: "SUNTRUST BANK", category: "Commercial" },
  { code: "302", name: "TAJ BANK", category: "Commercial" },
  { code: "102", name: "TITAN TRUST BANK", category: "Commercial" },
  { code: "033", name: "UNITED BANK FOR AFRICA (UBA)", category: "Commercial" },
  { code: "032", name: "UNION BANK", category: "Commercial" },
  { code: "215", name: "UNITY BANK", category: "Commercial" },
  { code: "039", name: "STANBIC IBTC BANK", category: "Commercial" },
  { code: "035", name: "WEMA BANK (ALAT)", category: "Commercial" },
  { code: "057", name: "ZENITH BANK", category: "Commercial" },

  // =========================
  // MICROFINANCE BANKS
  // =========================
  { code: "090270", name: "AB MICROFINANCE BANK", category: "Microfinance" },
  { code: "090260", name: "ABOVE ONLY MICROFINANCE BANK", category: "Microfinance" },
  { code: "090640", name: "ABSU MICROFINANCE BANK", category: "Microfinance" },
  { code: "090197", name: "ABU MICROFINANCE BANK", category: "Microfinance" },
  { code: "090545", name: "ABULESORO MICROFINANCE BANK", category: "Microfinance" },
  { code: "090134", name: "ACCION MICROFINANCE BANK", category: "Microfinance" },
  { code: "090483", name: "ADA MICROFINANCE BANK", category: "Microfinance" },
  { code: "090160", name: "ADDOSSER MICROFINANCE BANK", category: "Microfinance" },
  { code: "090268", name: "ADEYEMI COLLEGE STAFF MICROFINANCE BANK", category: "Microfinance" },
  { code: "090155", name: "ADVANS LA FAYETTE MICROFINANCE BANK", category: "Microfinance" },
  { code: "090292", name: "AFEKHAFE MICROFINANCE BANK", category: "Microfinance" },
  { code: "090518", name: "AFEMAI MICROFINANCE BANK", category: "Microfinance" },
  { code: "090608", name: "AKPO MICROFINANCE BANK", category: "Microfinance" },
  { code: "090531", name: "AKU MICROFINANCE BANK", category: "Microfinance" },
  { code: "090561", name: "AKUCHUKWU MICROFINANCE BANK", category: "Microfinance" },
  { code: "090133", name: "AL-BARAKAH MICROFINANCE BANK", category: "Microfinance" },
  { code: "090277", name: "AL-HAYAT MICROFINANCE BANK", category: "Microfinance" },
  { code: "090259", name: "ALEKUN MICROFINANCE BANK", category: "Microfinance" },
  { code: "090297", name: "ALERT MICROFINANCE BANK", category: "Microfinance" },
  { code: "090131", name: "ALLWORKERS MICROFINANCE BANK", category: "Microfinance" },
  { code: "090548", name: "ALLY MICROFINANCE BANK", category: "Microfinance" },
  { code: "090169", name: "ALPHA KAPITAL MICROFINANCE BANK", category: "Microfinance" },
  { code: "090489", name: "ALVANA MICROFINANCE BANK", category: "Microfinance" },
  { code: "090394", name: "AMAC MICROFINANCE BANK", category: "Microfinance" },
  { code: "090629", name: "AMEGY MICROFINANCE BANK", category: "Microfinance" },
  { code: "090180", name: "AMJU UNIQUE MICROFINANCE BANK", category: "Microfinance" },
  { code: "090116", name: "AMML MICROFINANCE BANK", category: "Microfinance" },
  { code: "090610", name: "AMOYE MICROFINANCE BANK", category: "Microfinance" },
  { code: "090529", name: "AMPERSAND MICROFINANCE BANK", category: "Microfinance" },
  { code: "090645", name: "AMUCHA MICROFINANCE BANK", category: "Microfinance" },
  { code: "090476", name: "ANCHORAGE MICROFINANCE BANK", category: "Microfinance" },
  { code: "090469", name: "ANIOCHA MICROFINANCE BANK", category: "Microfinance" },
  { code: "090143", name: "APEKS MICROFINANCE BANK", category: "Microfinance" },
  { code: "090376", name: "APPLE MICROFINANCE BANK", category: "Microfinance" },
  { code: "090307", name: "ARAMOKO MICROFINANCE BANK", category: "Microfinance" },
  { code: "090282", name: "ARISE MICROFINANCE BANK", category: "Microfinance" },
  { code: "090544", name: "ASPIRE MICROFINANCE BANK", category: "Microfinance" },
  { code: "090287", name: "ASSETMATRIX MICROFINANCE BANK", category: "Microfinance" },
  { code: "090473", name: "ASSETS MICROFINANCE BANK", category: "Microfinance" },
  { code: "090172", name: "ASTRAPOLARIS MICROFINANCE BANK", category: "Microfinance" },
  { code: "090264", name: "AUCHI MICROFINANCE BANK", category: "Microfinance" },
  { code: "090600", name: "AVE MARIA MICROFINANCE BANK", category: "Microfinance" },
  { code: "090633", name: "AWACASH MICROFINANCE BANK", category: "Microfinance" },
  { code: "090540", name: "AZTEC MICROFINANCE BANK", category: "Microfinance" },
  { code: "090625", name: "BABURA MFB", category: "Microfinance" },
  { code: "090188", name: "BAINES CREDIT MICROFINANCE BANK", category: "Microfinance" },
  { code: "090563", name: "BALERA MICROFINANCE BANK", category: "Microfinance" },
  { code: "090181", name: "BALOGUN FULANI MICROFINANCE BANK", category: "Microfinance" },
  { code: "090326", name: "BALOGUN GAMBARI MICROFINANCE BANK", category: "Microfinance" },
  { code: "090581", name: "BANC CORP MFB", category: "Microfinance" },
  { code: "090127", name: "BC KASH MICROFINANCE BANK", category: "Microfinance" },
  { code: "090618", name: "BERACHAH MFB", category: "Microfinance" },
  { code: "090615", name: "BESTSTAR MFB", category: "Microfinance" },
  { code: "090336", name: "BIPC MICROFINANCE BANK", category: "Microfinance" },
  { code: "090555", name: "BISHOPGATE MICROFINANCE BANK", category: "Microfinance" },
  { code: "090538", name: "BLUEPRINT INVESTMENTS MICROFINANCE BANK", category: "Microfinance" },
  { code: "090117", name: "BOCTRUST MICROFINANCE BANK", category: "Microfinance" },
  { code: "090444", name: "BOI MICROFINANCE BANK", category: "Microfinance" },
  { code: "090494", name: "BOJI MFB", category: "Microfinance" },
  { code: "090395", name: "BORGU MICROFINANCE BANK", category: "Microfinance" },
  { code: "090176", name: "BOSAK MICROFINANCE BANK", category: "Microfinance" },
  { code: "090148", name: "BOWEN MICROFINANCE BANK", category: "Microfinance" },
  { code: "090293", name: "BRETHREN MICROFINANCE BANK", category: "Microfinance" },
  { code: "090393", name: "BRIDGEWAY MICROFINANCE BANK", category: "Microfinance" },
  { code: "090308", name: "BRIGHTWAY MICROFINANCE BANK", category: "Microfinance" },
  { code: "090636", name: "BRIYTH-COVENANT MFB", category: "Microfinance" },
  { code: "090568", name: "BROADVIEW MICROFINANCE BANK", category: "Microfinance" },
  { code: "090655", name: "BUNKURE MFB", category: "Microfinance" },
  { code: "090406", name: "BUSINESS SUPPORT MICROFINANCE BANK", category: "Microfinance" },
  { code: "090647", name: "CANAAN MFB", category: "Microfinance" },
  { code: "090472", name: "CARETAKER MICROFINANCE BANK", category: "Microfinance" },
  { code: "090634", name: "CASHBRIDGE MFB", category: "Microfinance" },
  { code: "090360", name: "CASHCONNECT MICROFINANCE BANK", category: "Microfinance" },
  { code: "090649", name: "CASHRITE MFB", category: "Microfinance" },
  { code: "090562", name: "CEDAR MICROFINANCE BANK", category: "Microfinance" },
  { code: "090154", name: "CEMCS MICROFINANCE BANK", category: "Microfinance" },
  { code: "090470", name: "CHANGAN RTS MICROFINANCE BANK", category: "Microfinance" },
  { code: "090523", name: "CHASE MICROFINANCE BANK", category: "Microfinance" },
  { code: "090141", name: "CHIKUM MICROFINANCE BANK", category: "Microfinance" },
  { code: "090490", name: "CHUKWUNENYE MFB", category: "Microfinance" },
  { code: "090480", name: "CINTRUST MICROFINANCE BANK", category: "Microfinance" },
  { code: "090144", name: "CIT MICROFINANCE BANK", category: "Microfinance" },
  { code: "090254", name: "COALCAMP MICROFINANCE BANK", category: "Microfinance" },
  { code: "090374", name: "COASTLINE MICROFINANCE BANK", category: "Microfinance" },
  { code: "090530", name: "CONFIDENCE MFB", category: "Microfinance" },
  { code: "090380", name: "CONPRO MICROFINANCE BANK", category: "Microfinance" },
  { code: "090553", name: "CONSISTENT TRUST MICROFINANCE BANK", category: "Microfinance" },
  { code: "090130", name: "CONSUMER MICROFINANCE BANK", category: "Microfinance" },
  { code: "090365", name: "CORESTEP MICROFINANCE BANK", category: "Microfinance" },
  { code: "070006", name: "COVENANT MFB", category: "Microfinance" },
  { code: "090159", name: "CREDIT AFRIQUE MICROFINANCE BANK", category: "Microfinance" },
  { code: "090611", name: "CREDITVILLE MFB", category: "Microfinance" },
  { code: "090526", name: "CRESCENT MICROFINANCE BANK", category: "Microfinance" },
  { code: "090596", name: "DAL MFB", category: "Microfinance" },
  { code: "090391", name: "DAVODANI MICROFINANCE BANK", category: "Microfinance" },
  { code: "090167", name: "DAYLIGHT MICROFINANCE BANK", category: "Microfinance" },
  { code: "090643", name: "DIOBU MFB", category: "Microfinance" },
  { code: "090156", name: "E-BARCS MICROFINANCE BANK", category: "Microfinance" },
  { code: "090294", name: "EAGLE FLIGHT MICROFINANCE BANK", category: "Microfinance" },
  { code: "090310", name: "EDFIN MICROFINANCE BANK", category: "Microfinance" },
  { code: "090556", name: "EGWAFIN MICROFINANCE BANK", category: "Microfinance" },
  { code: "090389", name: "EK-RELIABLE MICROFINANCE BANK", category: "Microfinance" },
  { code: "090097", name: "EKONDO MFB", category: "Microfinance" },
  { code: "090273", name: "EMERALDS MICROFINANCE BANK", category: "Microfinance" },
  { code: "090114", name: "EMPIRE TRUST MFB", category: "Microfinance" },
  { code: "090539", name: "ENRICH MICROFINANCE BANK", category: "Microfinance" },
  { code: "090189", name: "ESAN MICROFINANCE BANK", category: "Microfinance" },
  { code: "090166", name: "ESO-E MICROFINANCE BANK", category: "Microfinance" },
  { code: "090304", name: "EVANGEL MICROFINANCE BANK", category: "Microfinance" },
  { code: "090332", name: "EVERGREEN MICROFINANCE BANK", category: "Microfinance" },
  { code: "090572", name: "EWT MICROFINANCE BANK", category: "Microfinance" },
  { code: "090541", name: "EXCELLENT MICROFINANCE BANK", category: "Microfinance" },
  { code: "090328", name: "EYOWO", category: "Microfinance" },
  { code: "090551", name: "FAIRMONEY MICROFINANCE BANK", category: "Microfinance" },
  { code: "090179", name: "FAST MICROFINANCE BANK", category: "Microfinance" },
  { code: "090409", name: "FCMB BETA", category: "Microfinance" },
  { code: "090290", name: "FCT MICROFINANCE BANK", category: "Microfinance" },
  { code: "090398", name: "FEDERAL POLYTECHNIC NEKEDE MICROFINANCE BANK", category: "Microfinance" },
  { code: "090318", name: "FEDERAL UNIVERSITY DUTSE MICROFINANCE BANK", category: "Microfinance" },
  { code: "090482", name: "FEDETH MICROFINANCE BANK", category: "Microfinance" },
  { code: "090298", name: "FEDPOLY NASARAWA MICROFINANCE BANK", category: "Microfinance" },
  { code: "090153", name: "FFS MICROFINANCE BANK", category: "Microfinance" },
  { code: "090126", name: "FIDFUND MICROFINANCE BANK", category: "Microfinance" },
  { code: "090507", name: "FIMS MFB", category: "Microfinance" },
  { code: "090111", name: "FINATRUST MICROFINANCE BANK", category: "Microfinance" },
  { code: "090400", name: "FINCA MICROFINANCE BANK", category: "Microfinance" },
  { code: "090366", name: "FIRMUS MICROFINANCE BANK", category: "Microfinance" },
  { code: "090575", name: "FIRST MIDAS MICROFINANCE BANK", category: "Microfinance" },
  { code: "090285", name: "FIRST OPTION MICROFINANCE BANK", category: "Microfinance" },
  { code: "090164", name: "FIRST ROYAL MICROFINANCE BANK", category: "Microfinance" },
  { code: "090614", name: "FLOURISH MFB", category: "Microfinance" },
  { code: "070002", name: "FORTIS MICROFINANCE BANK", category: "Microfinance" },
  { code: "090145", name: "FULLRANGE MICROFINANCE BANK", category: "Microfinance" },
  { code: "090158", name: "FUTO MICROFINANCE BANK", category: "Microfinance" },
  { code: "090582", name: "GABASAWA MFB", category: "Microfinance" },
  { code: "090591", name: "GABSYn MICROFINANCE BANK LIMITED", category: "Microfinance" },
  { code: "090168", name: "GASHUA MICROFINANCE BANK", category: "Microfinance" },
  { code: "090579", name: "GBEDE MICROFINANCE BANK", category: "Microfinance" },
  { code: "090475", name: "GIANT STRIDE MICROFINANCE BANK", category: "Microfinance" },
  { code: "090621", name: "GIDAUNIYAR ALHERI MFB", category: "Microfinance" },
  { code: "090411", name: "GIGINYA MICROFINANCE BANK", category: "Microfinance" },
  { code: "090186", name: "GIREI MICROFINANCE BANK", category: "Microfinance" },
  { code: "090639", name: "GLOBAL INITIATIVE MFB", category: "Microfinance" },
  { code: "090278", name: "GLORY MICROFINANCE BANK", category: "Microfinance" },
  { code: "090408", name: "GMB MICROFINANCE BANK", category: "Microfinance" },
  { code: "090574", name: "GOLDMAN MFB", category: "Microfinance" },
  { code: "090586", name: "GOMBE MFB", category: "Microfinance" },
  { code: "090467", name: "GOOD NEIGHBOURS MICROFINANCE BANK", category: "Microfinance" },
  { code: "090495", name: "GOODNEWS MICROFINANCE BANK", category: "Microfinance" },
  { code: "090122", name: "GOWANS MICROFINANCE BANK", category: "Microfinance" },
  { code: "090550", name: "GREEN ENERGY MICROFINANCE BANK", category: "Microfinance" },
  { code: "090178", name: "GREENBANK MICROFINANCE BANK", category: "Microfinance" },
  { code: "090269", name: "GREENVILLE MICROFINANCE BANK", category: "Microfinance" },
  { code: "090195", name: "GROOMING MICROFINANCE BANK", category: "Microfinance" },
  { code: "090385", name: "GTI MICROFINANCE BANK", category: "Microfinance" },
  { code: "090147", name: "HACKMAN MICROFINANCE BANK", category: "Microfinance" },
  { code: "090291", name: "HALAL CREDIT MICROFINANCE BANK", category: "Microfinance" },
  { code: "090121", name: "HASAL MICROFINANCE BANK", category: "Microfinance" },
  { code: "090363", name: "HEADWAY MICROFINANCE BANK", category: "Microfinance" },
  { code: "090175", name: "HIGHSTREET MICROFINANCE BANK", category: "Microfinance" },
  { code: "090598", name: "IBA MICROFINANCE BANK", category: "Microfinance" },
  { code: "090118", name: "IBILE MICROFINANCE BANK", category: "Microfinance" },
  { code: "090532", name: "IBOLO MICROFINANCE BANK", category: "Microfinance" },
  { code: "090519", name: "IBOMA FADAMA MICROFINANCE BANK", category: "Microfinance" },
  { code: "090488", name: "IBU-AJE MICROFINANCE BANK", category: "Microfinance" },
  { code: "090546", name: "IJEBU-IFE MICROFINANCE BANK", category: "Microfinance" },
  { code: "090324", name: "IKENNE MICROFINANCE BANK", category: "Microfinance" },
  { code: "090279", name: "IKIRE MICROFINANCE BANK", category: "Microfinance" },
  { code: "090536", name: "IKOYI-OSUN MICROFINANCE BANK", category: "Microfinance" },
  { code: "090571", name: "ILARO POLY MICROFINANCE BANK", category: "Microfinance" },
  { code: "090370", name: "ILISAN MICROFINANCE BANK", category: "Microfinance" },
  { code: "090258", name: "IMO STATE MICROFINANCE BANK", category: "Microfinance" },
  { code: "090157", name: "INFINITY MICROFINANCE BANK", category: "Microfinance" },
  { code: "090386", name: "INTERLAND MICROFINANCE BANK", category: "Microfinance" },
  { code: "090149", name: "IRL MICROFINANCE BANK", category: "Microfinance" },
  { code: "090377", name: "ISALEOYO MICROFINANCE BANK", category: "Microfinance" },
  { code: "090584", name: "ISLAND MICROFINANCE BANK", category: "Microfinance" },
  { code: "090578", name: "IWADE MFB LTD", category: "Microfinance" },
  { code: "090543", name: "IWOAMA MICROFINANCE BANK", category: "Microfinance" },
  { code: "090570", name: "IYAMOYE MICROFINANCE BANK", category: "Microfinance" },
  { code: "090337", name: "IYERU OKIN MICROFINANCE BANK", category: "Microfinance" },
  { code: "090620", name: "IYIN EKITI MFB", category: "Microfinance" },
  { code: "090352", name: "JESSEFIELD MICROFINANCE BANK", category: "Microfinance" },
  { code: "090320", name: "KADPOLY MICROFINANCE BANK", category: "Microfinance" },
  { code: "090554", name: "KAYVEE MICROFINANCE BANK", category: "Microfinance" },
  { code: "090549", name: "KC MICROFINANCE BANK", category: "Microfinance" },
  { code: "090191", name: "KCMB MICROFINANCE BANK", category: "Microfinance" },
  { code: "090602", name: "KENECHUKWU MICROFINANCE BANK", category: "Microfinance" },
  { code: "090606", name: "KKU MFB", category: "Microfinance" },
  { code: "090299", name: "KONTAGORA MICROFINANCE BANK", category: "Microfinance" },
  { code: "090617", name: "KOPO KOPE MFB", category: "Microfinance" },
  { code: "090267", name: "KUDA MICROFINANCE BANK", category: "Microfinance" },
  { code: "090177", name: "LAPO MICROFINANCE BANK", category: "Microfinance" },
  { code: "090271", name: "LAVENDER MICROFINANCE BANK", category: "Microfinance" },
  { code: "090650", name: "LEADCITY MFB", category: "Microfinance" },
  { code: "090372", name: "LEGEND MICROFINANCE BANK", category: "Microfinance" },
  { code: "090557", name: "LIFEGATE MICROFINANCE BANK", category: "Microfinance" },
  { code: "090477", name: "LIGHT MFB", category: "Microfinance" },
  { code: "090537", name: "LOBREM MICROFINANCE BANK", category: "Microfinance" },
  { code: "090265", name: "LOVONUS MICROFINANCE BANK", category: "Microfinance" },
  { code: "090623", name: "MAB ALLIANZ MFB", category: "Microfinance" },
  { code: "090630", name: "MABINAS MFB", category: "Microfinance" },
  { code: "090603", name: "MACROD MFB", category: "Microfinance" },
  { code: "090605", name: "MADOBI MFB", category: "Microfinance" },
  { code: "090323", name: "MAINLAND MICROFINANCE BANK", category: "Microfinance" },
  { code: "090171", name: "MAINSTREET MICROFINANCE BANK", category: "Microfinance" },
  { code: "090465", name: "MAINTRUST MICROFINANCE BANK", category: "Microfinance" },
  { code: "090174", name: "MALACHY MICROFINANCE BANK", category: "Microfinance" },
  { code: "090410", name: "MARITIME MICROFINANCE BANK", category: "Microfinance" },
  { code: "090321", name: "MAYFAIR MICROFINANCE BANK", category: "Microfinance" },
  { code: "090612", name: "MEDEF MICROFINANCE BANK", category: "Microfinance" },
  { code: "090280", name: "MEGAPRAISE MICROFINANCE BANK", category: "Microfinance" },
  { code: "090589", name: "MERCURY MFB", category: "Microfinance" },
  { code: "090528", name: "MGBIDI MICROFINANCE BANK", category: "Microfinance" },
  { code: "090659", name: "MICHAEL OKPARA UNIAGRIC MICROFINANCE BANK", category: "Microfinance" },
  { code: "090587", name: "MICROBIZ MFB", category: "Microfinance" },
  { code: "090136", name: "MICROCRED MICROFINANCE BANK", category: "Microfinance" },
  { code: "090192", name: "MIDLAND MICROFINANCE BANK", category: "Microfinance" },
  { code: "090607", name: "MINJIBIR MFB", category: "Microfinance" },
  { code: "090281", name: "MINTFINEX MICROFINANCE BANK", category: "Microfinance" },
  { code: "090455", name: "MKobo MICROFINANCE BANK", category: "Microfinance" },
  { code: "090362", name: "MOLUSI MICROFINANCE BANK", category: "Microfinance" },
  { code: "090129", name: "MONEY TRUST MICROFINANCE BANK", category: "Microfinance" },
  { code: "090405", name: "MONIEPOINT MICROFINANCE BANK", category: "Microfinance" },
  { code: "090448", name: "MOYOFADE MICROFINANCE BANK", category: "Microfinance" },
  { code: "090190", name: "MUTUAL BENEFITS MICROFINANCE BANK", category: "Microfinance" },
  { code: "090151", name: "MUTUAL TRUST MICROFINANCE BANK", category: "Microfinance" },
  { code: "090152", name: "NAGARTA MICROFINANCE BANK", category: "Microfinance" },
  { code: "090349", name: "NASSARAWA MICROFINANCE BANK", category: "Microfinance" },
  { code: "090263", name: "NAVY MICROFINANCE BANK", category: "Microfinance" },
  { code: "090128", name: "NDIORAH MICROFINANCE BANK", category: "Microfinance" },
  { code: "090329", name: "NEPTUNE MICROFINANCE BANK", category: "Microfinance" },
  { code: "090205", name: "NEW DAWN MICROFINANCE BANK", category: "Microfinance" },
  { code: "090378", name: "NEW GOLDEN PASTURES MICROFINANCE BANK", category: "Microfinance" },
  { code: "090505", name: "NIGERIAN PRISONS MICROFINANCE BANK", category: "Microfinance" },
  { code: "090194", name: "NIRSAL MICROFINANCE BANK", category: "Microfinance" },
  { code: "090535", name: "NKPOLU-UST MFB", category: "Microfinance" },
  { code: "090283", name: "NNEW WOMEN MICROFINANCE BANK", category: "Microfinance" },
  { code: "070001", name: "NPF MICROFINANCE BANK", category: "Microfinance" },
  { code: "090628", name: "NSEHE MFB", category: "Microfinance" },
  { code: "090491", name: "NSUK MFB", category: "Microfinance" },
  { code: "090516", name: "NUMO MICROFINANCE BANK", category: "Microfinance" },
  { code: "090364", name: "NUTURE MICROFINANCE BANK", category: "Microfinance" },
  { code: "090399", name: "NWANNEGADI MICROFINANCE BANK", category: "Microfinance" },
  { code: "090345", name: "OAU MICROFINANCE BANK", category: "Microfinance" },
  { code: "090333", name: "OCHE MICROFINANCE BANK", category: "Microfinance" },
  { code: "090576", name: "OCTOPUS MICROFINANCE BANK", category: "Microfinance" },
  { code: "090654", name: "ODOAKPU MFB", category: "Microfinance" },
  { code: "090119", name: "OHAFIA MICROFINANCE BANK", category: "Microfinance" },
  { code: "090626", name: "OHHA MFB", category: "Microfinance" },
  { code: "090527", name: "OJOKORO MICROFINANCE BANK", category: "Microfinance" },
  { code: "090565", name: "OKE-ARO OREDEGBE MICROFINANCE BANK", category: "Microfinance" },
  { code: "090646", name: "OKENGWE MFB", category: "Microfinance" },
  { code: "090161", name: "OKPOGA MICROFINANCE BANK", category: "Microfinance" },
  { code: "090566", name: "OKUKU MICROFINANCE BANK", category: "Microfinance" },
  { code: "090272", name: "OLABISI ONABANJO UNIVERSITY MICROFINANCE BANK", category: "Microfinance" },
  { code: "090404", name: "OLOWOLAGBA MICROFINANCE BANK", category: "Microfinance" },
  { code: "090471", name: "OLUCHUKWU MICROFINANCE BANK", category: "Microfinance" },
  { code: "090295", name: "OMIYE MICROFINANCE BANK", category: "Microfinance" },
  { code: "100004", name: "OPAY (PAYCOM)", category: "Microfinance" },
  { code: "090492", name: "ORAUKWU MFB", category: "Microfinance" },
  { code: "090588", name: "ORISUN MFB", category: "Microfinance" },
  { code: "090567", name: "OROKAM MICROFINANCE BANK", category: "Microfinance" },
  { code: "090396", name: "OSCOTECH MICROFINANCE BANK", category: "Microfinance" },
  { code: "090580", name: "OTECH MICROFINANCE BANK", category: "Microfinance" },
  { code: "", name: "OTHER MFB" },
  { code: "090542", name: "OTUO MICROFINANCE BANK", category: "Microfinance" },
  { code: "090635", name: "OYAN MFB", category: "Microfinance" },
  { code: "070008", name: "PAGE FINANCIALS", category: "Microfinance" },
  { code: "100033", name: "PALMPAY", category: "Microfinance" },
  { code: "090004", name: "PARRALEX MICROFINANCE BANK", category: "Microfinance" },
  { code: "090317", name: "PATRICKGOLD MICROFINANCE BANK", category: "Microfinance" },
  { code: "090137", name: "PECANTRUST MICROFINANCE BANK", category: "Microfinance" },
  { code: "090196", name: "PENNYWISE MICROFINANCE BANK", category: "Microfinance" },
  { code: "090135", name: "PERSONAL TRUST MICROFINANCE BANK", category: "Microfinance" },
  { code: "090165", name: "PETRA MICROFINANCE BANK", category: "Microfinance" },
  { code: "090289", name: "PILLAR MICROFINANCE BANK", category: "Microfinance" },
  { code: "090534", name: "POLYBADAN MICROFINANCE BANK", category: "Microfinance" },
  { code: "090296", name: "POLYUNWANA MICROFINANCE BANK", category: "Microfinance" },
  { code: "090412", name: "PREEMINENT MICROFINANCE BANK", category: "Microfinance" },
  { code: "090274", name: "PRESTIGE MICROFINANCE BANK", category: "Microfinance" },
  { code: "090499", name: "PRISTINE DIVITIS MICROFINANCE BANK", category: "Microfinance" },
  { code: "090503", name: "PROJECTS MICROFINANCE BANK", category: "Microfinance" },
  { code: "090642", name: "PROSPERITY MFB", category: "Microfinance" },
  { code: "090303", name: "PURPLEMONEY MICROFINANCE BANK", category: "Microfinance" },
  { code: "090657", name: "PYRAMID MFB", category: "Microfinance" },
  { code: "090569", name: "QUBE MICROFINANCE BANK", category: "Microfinance" },
  { code: "090261", name: "QUICKFUND MICROFINANCE BANK", category: "Microfinance" },
  { code: "090496", name: "RANDALPHA MICROFINANCE BANK", category: "Microfinance" },
  { code: "090616", name: "RAYYAN MFB", category: "Microfinance" },
  { code: "090125", name: "REGENT MICROFINANCE BANK", category: "Microfinance" },
  { code: "090463", name: "REHOBOTH MICROFINANCE BANK", category: "Microfinance" },
  { code: "090173", name: "RELIANCE MICROFINANCE BANK", category: "Microfinance" },
  { code: "090198", name: "RENMONEY MICROFINANCE BANK", category: "Microfinance" },
  { code: "090322", name: "REPHIDIM MICROFINANCE BANK", category: "Microfinance" },
  { code: "090132", name: "RICHWAY MICROFINANCE BANK", category: "Microfinance" },
  { code: "090433", name: "RIGO MICROFINANCE BANK", category: "Microfinance" },
  { code: "090515", name: "RIMA GROWTH PATHWAY MICROFINANCE BANK", category: "Microfinance" },
  { code: "090547", name: "ROCKSHIELD MICROFINANCE BANK", category: "Microfinance" },
  { code: "090622", name: "ROYAL BLUE MFB", category: "Microfinance" },
  { code: "090138", name: "ROYAL EXCHANGE MICROFINANCE BANK", category: "Microfinance" },
  { code: "090286", name: "SAFE HAVEN MICROFINANCE BANK", category: "Microfinance" },
  { code: "090140", name: "SAGAMU MICROFINANCE BANK", category: "Microfinance" },
  { code: "090513", name: "SEAP MICROFINANCE BANK", category: "Microfinance" },
  { code: "090112", name: "SEED CAPITAL MICROFINANCE BANK", category: "Microfinance" },
  { code: "090369", name: "SEEDVEST MICROFINANCE BANK", category: "Microfinance" },
  { code: "090502", name: "SHALOM MICROFINANCE BANK", category: "Microfinance" },
  { code: "090401", name: "SHEPHERD TRUST MICROFINANCE BANK", category: "Microfinance" },
  { code: "090559", name: "SHIELD MICROFINANCE BANK", category: "Microfinance" },
  { code: "090558", name: "SHONGOM MICROFINANCE BANK", category: "Microfinance" },
  { code: "090573", name: "SNOW MFB", category: "Microfinance" },
  { code: "090506", name: "SOLID ALLIANZE MFB", category: "Microfinance" },
  { code: "090524", name: "SOLIDROCK MICROFINANCE BANK", category: "Microfinance" },
  { code: "090641", name: "SOURCE MFB", category: "Microfinance" },
  { code: "090325", name: "SPARKLE", category: "Microfinance" },
  { code: "090162", name: "STANFORD MICROFINANCE BANK", category: "Microfinance" },
  { code: "090583", name: "STATESIDE MICROFINANCE BANK", category: "Microfinance" },
  { code: "090262", name: "STELLAS MICROFINANCE BANK", category: "Microfinance" },
  { code: "090305", name: "SULSPAP MICROFINANCE BANK", category: "Microfinance" },
  { code: "090644", name: "SUNTOP MFB", category: "Microfinance" },
  { code: "090564", name: "SUPREME MICROFINANCE BANK", category: "Microfinance" },
  { code: "090560", name: "TANADI MICROFINANCE BANK", category: "Microfinance" },
  { code: "090638", name: "TANGALE MFB", category: "Microfinance" },
  { code: "090593", name: "TASUED MICROFINANCE BANK", category: "Microfinance" },
  { code: "090115", name: "TCF MFB", category: "Microfinance" },
  { code: "090373", name: "THINK FINANCE MICROFINANCE BANK", category: "Microfinance" },
  { code: "090613", name: "TOTAL TRUST MFB", category: "Microfinance" },
  { code: "090146", name: "TRIDENT MICROFINANCE BANK", category: "Microfinance" },
  { code: "090525", name: "TRIPLEA MICROFINANCE BANK", category: "Microfinance" },
  { code: "090327", name: "TRUST MICROFINANCE BANK", category: "Microfinance" },
  { code: "090276", name: "TRUSTFUND MICROFINANCE BANK", category: "Microfinance" },
  { code: "090315", name: "U & C MICROFINANCE BANK", category: "Microfinance" },
  { code: "090403", name: "UDA MICROFINANCE BANK", category: "Microfinance" },
  { code: "090517", name: "UHURU MICROFINANCE BANK", category: "Microfinance" },
  { code: "090609", name: "UMMAH MICROFINANCE BANK", category: "Microfinance" },
  { code: "090632", name: "UMUCHUKWU MFB", category: "Microfinance" },
  { code: "090331", name: "UNAAB MICROFINANCE BANK", category: "Microfinance" },
  { code: "090266", name: "UNIBEN MICROFINANCE BANK", category: "Microfinance" },
  { code: "090193", name: "UNICAL MICROFINANCE BANK", category: "Microfinance" },
  { code: "090637", name: "UNIFUND MFB", category: "Microfinance" },
  { code: "090464", name: "UNIMAID MICROFINANCE BANK", category: "Microfinance" },
  { code: "090338", name: "UNIUYO MICROFINANCE BANK", category: "Microfinance" },
  { code: "090251", name: "UNN MFB", category: "Microfinance" },
  { code: "090474", name: "VERDANT MICROFINANCE BANK", category: "Microfinance" },
  { code: "090123", name: "VERITE MICROFINANCE BANK", category: "Microfinance" },
  { code: "090110", name: "VFD MFB", category: "Microfinance" },
  { code: "090150", name: "VIRTUE MICROFINANCE BANK", category: "Microfinance" },
  { code: "090139", name: "VISA MICROFINANCE BANK", category: "Microfinance" },
  { code: "090950", name: "WAYA MICROFINANCE BANK", category: "Microfinance" },
  { code: "090120", name: "WETLAND MICROFINANCE BANK", category: "Microfinance" },
  { code: "090124", name: "XSLNCE MICROFINANCE BANK", category: "Microfinance" },
  { code: "090466", name: "YCT MICROFINANCE BANK", category: "Microfinance" },
  { code: "090142", name: "YES MICROFINANCE BANK", category: "Microfinance" },
  { code: "090252", name: "YOBE MICROFINANCE BANK", category: "Microfinance" },
  { code: "090504", name: "ZIKORA MICROFINANCE BANK", category: "Microfinance" },
  { code: "090175", name: "RUBIES MICROFINANCE BANK", category: "Microfinance" },
];

// Sort alphabetically by bank name for easier searching
const sortedBankCodes = [...BANK_CODES].sort((a, b) => 
  a.name.localeCompare(b.name)
);

export default sortedBankCodes;
